### ISSUE TITLE
Missing globals from 0.1.0 release

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-globals#2]
e.g. SECURE_AUTH_KEY is missing in the stubs, but defined in the wp-config(-sample).php

Can you add that?

**Comment by szepeviktor** [comment]
Hello @kkmuffme 👋 
This is the dirtiest project I have.

I see your constant here https://github.com/php-stubs/wordpress-globals/blob/748a1fb2ae8fda94844bd0545935095dbf404b32/source/wp-config.php#L10

**Comment by szepeviktor** [comment]
And in the stubs file 😲 
https://github.com/php-stubs/wordpress-globals/blob/748a1fb2ae8fda94844bd0545935095dbf404b32/wordpress-globals.php#L145

**Comment by kkmuffme** [comment]
Ah sorry, for some reason I downloaded the 0.1.0 release instead of the latest.
