### ISSUE TITLE
Psalm and calculated constants

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-globals#3]
Psalm struggles with calculated constants:

```php
define( 'MB_IN_BYTES', 1024 * KB_IN_BYTES );
define( 'GB_IN_BYTES', 1024 * MB_IN_BYTES );
define( 'TB_IN_BYTES', 1024 * GB_IN_BYTES );

define( 'HOUR_IN_SECONDS', 60 * MINUTE_IN_SECONDS );
define( 'DAY_IN_SECONDS', 24 * HOUR_IN_SECONDS );
define( 'WEEK_IN_SECONDS', 7 * DAY_IN_SECONDS );
define( 'MONTH_IN_SECONDS', 30 * DAY_IN_SECONDS );
define( 'YEAR_IN_SECONDS', 365 * DAY_IN_SECONDS );
```

(I already fixed it manually for my fork, is it possible to automatically generate it with dynamic values in this repo?)

**Comment by szepeviktor** [comment]
Hello @kkmuffme !

This project is an ill-fated orphan.
I'm sorry.

**Comment by szepeviktor** [comment]
Please see the very fist item on the _What to avoid_ list 😉
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md#what-to-avoid

**Comment by kkmuffme** [comment]
I don't own WordPress, but I need to develop for it, which I guess this repo is for :-) I can't change WordPress but merely workaround it's issues. e.g. WP_DEBUG, ... are stuff that are out of my control, but will get flagged by psalm, if I don't use stubs.

**Comment by szepeviktor** [comment]
Please be creative!
